// Starter category-name ideas seeded into data/categories.json on first run.
// This is just a pool of topic names to pick from — you write the questions yourself.
// Edit, delete, or expand this list in the Board Editor's Category DB.

export const STARTER_CATEGORIES: string[] = [
  "Allgemeinwissen",
  "Geschichte",
  "Geographie",
  "Wissenschaft",
  "Biologie",
  "Physik",
  "Chemie",
  "Mathematik",
  "Musik",
  "Film & Fernsehen",
  "Serien",
  "Literatur",
  "Kunst",
  "Sport",
  "Fußball",
  "Technik",
  "Computer & Internet",
  "Videospiele",
  "Essen & Trinken",
  "Tiere",
  "Natur",
  "Weltraum & Astronomie",
  "Politik",
  "Wirtschaft",
  "Religion & Mythologie",
  "Sprachen",
  "Berühmte Persönlichkeiten",
  "Erfindungen & Entdeckungen",
  "Automarken",
  "Länder & Hauptstädte",
  "Flaggen",
  "Musikinstrumente",
  "Comics & Superhelden",
  "Märchen & Sagen",
  "Redewendungen",
  "Abkürzungen",
  "Logos & Marken",
  "Feiertage & Bräuche",
  "Deutschland",
  "Popkultur",
];
